docker/Dockerfile
for for #4 - Docker build not pulling the latest source code.
Im writing some small random number so that cache invalidates and repo is freshly cloned
=> fix for bug #4 - Docker build not pulling the latest source code.

Etaler/Core/Tensor.cpp, tests/common_tests.cpp
=> Implement truncation when printing large tensors

Etaler/Algorithms/Boost.hpp, Etaler/Core/Tensor.cpp
Yeah... I s***ed up. Wrong equation to calculate boost factor. Fixed
=> Fix boosting with the wrong equation.

CMakeLists.txt, cmake/FindTBB.cmake
=> add FindTBB.cmake since distrods might not ship it

Etaler/Algorithms/SDRClassifer.hpp, Etaler/Algorithms/SpatialPooler.hpp, Etaler/Algorithms/TemporalMemory.hpp
=> add copy() function to all layers

Etaler/Backends/OpenCLBackend.cpp, Etaler/Backends/OpenCLBackend.hpp, Etaler/Core/String.hpp
This PR makes the OpenCL backend check that the device it is running on supports the required extensions.
This is also a required feature to support FP16 for OpenCL. See #12
=> Check for requied OpenCL extention

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .gitignore
Hi  Martin,
This PR add drivers for OpenCL inside docker..
Enjoy
Lior
=> Adding support for OpenCL inside docker

Etaler/Algorithms/SpatialPooler.cpp, Etaler/Algorithms/SpatialPooler.hpp, Etaler/Algorithms/SpatialPoolerND.cpp, Etaler/Algorithms/SpatialPoolerND.hpp
fix #49
Now SpatialPoolerND is the version with topology support.
=> move SpatialPooler w topology to another class

examples/tmexample.cpp, examples/visualize/tm_visualize.cpp
=> fix TM bursting when it shouldn't

.gitmodules, README.md, examples/CMakeLists.txt
=>  add switch to disable visualizer 

Etaler/Backends/OpenCLBackend.cpp, Etaler/Core/Tensor.hpp, tests/common_tests.cpp
fix #65 and other optimizations
=> OpenCLBackend fixes and enhensments

Etaler/Algorithms/SpatialPoolerND.cpp, Etaler/Algorithms/SpatialPoolerND.hpp, Etaler/Backends/OpenCLBackend.cpp, Etaler/CMakeLists.txt
=> fix SpatialPoolerND

Etaler/Backends/CPUBackend.cpp, Etaler/Interop/Arrayfire.hpp, examples/tmbench.cpp, examples/tmexample.cpp, kernels/globalInhibition.cl
I'm lazy to name my PRs now. Anyway...
fix #67 among other improvements.
=> A batch of updates

Etaler/Backends/OpenCLBackend.cpp, kernels/globalInhibition.cl, kernels/reverseBurst.cl
Fix TM on OpenCL underperforming compare to CPU (prediction capability wise).
related to #67
=> Fix TM on OpenCL underperforming compare to CPU

Etaler/Backends/OpenCLBackend.hpp, Etaler/Core/Tensor.hpp, docs/Tensor.md
=> Batch of updates

Etaler/Core/Tensor.hpp, tests/common_tests.cpp
=> implement [] operator

Etaler/Backends/CPUBackend.cpp, Etaler/Core/Views.hpp, docs/PythonBindings.md, docs/Tensor.md
=> Fix tbb warning

docs/PythonBindings.md, examples/mnist.cpp
This PR fixes the bug where the MNIST example can't load data even if data existed in the specified folder.
=> Fix MNIST Error

Etaler/Algorithms/SDRClassifer.hpp, Etaler/Backends/OpenCLBackend.cpp, Etaler/Core/Serialize.hpp, tests/common_tests.cpp
=> Recent bug fixes

README.md, cmake/FindSphinx.cmake, docs/CMakeLists.txt, docs/source/conf.py, docs/source/index.rst
Again, more updates regarding the docs
=> More document updates

CMakeLists.txt, Etaler/Backends/CPUBackend.hpp, Etaler/Backends/OpenCLBackend.hpp, Etaler/CMakeLists.txt, Etaler/Core/TensorImpl.hpp
fix #105 
Fixes Backend/Buffer visiblity so PyEtaler can load backend properly
=> Fix Backend/Buffer visiblity

README.md, docs/source/BackendDesign.md, docs/source/BuildOnLinux.md, docs/source/BuildOnOSX.md, docs/source/Introduction.md, docs/source/index.rst, tests/common_tests.cpp
Just adding more documents and removing errors in docs.
=> Add more documentations

.gitmodules, examples/visualize/CMakeLists.txt
fix #110 
This PR along with https://github.com/marty1885/LayersVisualizer/commit/3ca500e4e63f7f62dd874d3dfc05b6767b615f90 should fix the problem.
=> Fix imgui linking

Etaler/Core/Tensor.cpp, Etaler/Core/Tensor.hpp, Etaler/Core/Views.hpp, tests/common_tests.cpp
This PR turns the hacky range system into a robust/pythonic one. Now we support:
* arbitrary step size
* Proper indexing error message
* use std::optional to handle missing range values
=> Improve step support in indexing

docs/images/gc1d_overlap.svg, docs/source/HTMAlgorithm.md, docs/source/conf.py, docs/source/index.rst
Add tutorial about
* Encoder
* Anomaly
* Temporal Memory
* Spatial Pooler
=> Add HTM algorithm tutorial

docs/requirements.txt
=> attempt to fix RtD build fail

Etaler/Core/Tensor.cpp, Etaler/Core/Tensor.hpp, docs/source/HTMAlgorithm.md, tests/common_tests.cpp
fix #116 
And add support for negative dimension index. If the index is negative, it is counted backwards.
=> Enhence sum()

Etaler/Algorithms/Boost.hpp, Etaler/Backends/CPUBackend.cpp, Etaler/Backends/OpenCLBackend.cpp, Etaler/Core/Tensor.cpp, Etaler/Core/Tensor.hpp, docs/source/PythonBindings.md, kernels/sum_local.cl
fix #118 
Now sum() is a lot faster than it was when dealing with generating small amount of results.
=> sum() performance optimizations

Etaler/Backends/OpenCLBackend.cpp, Etaler/Core/Tensor.cpp, Etaler/Core/Tensor.hpp, Etaler/Core/TensorImpl.hpp, tests/common_tests.cpp
=> Make tensor support iteration

Etaler/Algorithms/SpatialPooler.hpp, Etaler/Core/Tensor.cpp, Etaler/Core/Tensor.hpp, Etaler/Core/Views.hpp, Etaler/Encoders/Category.hpp, docs/source/Contribution.md, tests/common_tests.cpp
Mostly fixing bugs before changing the API is possible.
=> Mostly fixing bugs

Etaler/Backends/CPUBackend.cpp, Etaler/Backends/CPUBackend.hpp, Etaler/Backends/OpenCLBackend.cpp, Etaler/Backends/OpenCLBackend.hpp, Etaler/Core/Backend.hpp, Etaler/Core/Tensor.cpp, Etaler/Core/Tensor.hpp, Etaler/Core/TypeHelpers.hpp, tests/common_tests.cpp
1. any()/all()
2. Unit test on STL alforithms
3. Improved iterators
4. abs()
=> another batch of needed additional features

Etaler/Algorithms/SpatialPoolerND.cpp, Etaler/Backends/CPUBackend.cpp, Etaler/Core/Tensor.cpp, Etaler/Core/Tensor.hpp, Etaler/Core/Views.hpp, tests/common_tests.cpp
=> Rework indexing system

Etaler/Backends/OpenCLBackend.cpp, Etaler/Core/Tensor.cpp, kernels/copy.cl, tests/common_tests.cpp
* Don't JIT for copying data
* Simplify indexing logic
* Add faster indexing path for simple cases
=> Optimize OpenCL indexing time

Etaler/Core/Tensor.hpp, docs/source/PythonBindings.md, tests/common_tests.cpp
* use () for indexing
* xtensor style indexing
=> more indexing method

.gitmodules, Etaler/Algorithms/SpatialPooler.cpp, Etaler/Algorithms/SpatialPooler.hpp, Etaler/Algorithms/SpatialPoolerND.cpp, Etaler/Algorithms/Synapse.cpp, Etaler/Algorithms/Synapse.hpp, Etaler/Backends/CPUBackend.cpp, Etaler/Backends/OpenCLBackend.cpp, Etaler/CMakeLists.txt, Etaler/Core/Shape.hpp, Etaler/Core/Tensor.hpp, tests/common_tests.cpp
mainly more tests and initial attempts to fix the synaptic generation process
=> more testing

CMakeLists.txt, Etaler/Backends/CPUBackend.cpp, Etaler/Backends/OpenCLBackend.cpp, Etaler/Core/Error.hpp, Etaler/Core/Tensor.hpp, cmake/EnableSIMD.cmake, tests/common_tests.cpp
* Fix where IsPlain should be used instead of IsContingous
* copy() can copy from offset
* Enable SIMD on x86 and ARM64
* RISC-V and PPC64 not supported as of now
* Clean clang build (no warnings)
=> Various bug fixes and performence improvments

Etaler/Core/Shape.hpp
=> fix assert typos in Etaler/Core/Shape.hpp

Etaler/Core/Backend.hpp, Etaler/Core/Shape.hpp, Etaler/Core/Tensor.cpp, LICENSE, examples/example1.cpp, tests/common_tests.cpp
Mainly:
* Mark Backends as not copy able
* Optimize printing tensor
* Fix a few compiler warnings
=> New batch of changes

Etaler/Algorithms/Anomaly.hpp, Etaler/Algorithms/TemporalMemory.cpp, Etaler/Core/Backend.hpp, Etaler/Core/Error.cpp, Etaler/Core/Error.hpp, Etaler/Core/Serialize.cpp, Etaler/Core/Tensor.cpp, docs/source/DeveloperNotes.md, tests/common_tests.cpp
Fix #146 among other issues. but the msvc compiler bug is really annoning.
=> WIP: Make Etaler build on MSVC again

Etaler/Backends/OpenCLBackend.cpp, Etaler/Core/Shape.hpp, Etaler/Core/SmallVector.hpp, Etaler/Core/Tensor.hpp, README.md, docs/source/DeveloperNotes.md
Fix #158 
* Add FreeBSD to supported OS
* Add Clover to supported OpenCL SDK
* various bug fixes
=> Various updates
